import { StyleSheet } from "react-native";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";


export const Cartstyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F5F6FC",
  },
  container: {
    flex: 1,
    paddingHorizontal: wp("4%"),
    backgroundColor: "#F5F6FC",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    marginTop: hp("2.5%"),
    fontSize: wp("5%"),
    fontWeight: "600",
    marginLeft: wp("2%"),
  },
  addressRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: wp("2%"),
    padding: wp("3%"),
    marginTop: hp("2%"),
  },
  addressText: {
    marginHorizontal: wp("2%"),
    color: "#283593",
    fontWeight: "500",
    flex: 1,
  },
  cartCard: {
    borderRadius: wp("4%"),
    marginVertical: hp("1%"),
    padding: wp("3%"),
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: wp("2.5%"),
  },
  cartItemBox: {
    height: hp("67%"),
    borderRadius: wp("2%"),
    backgroundColor: "#fff",
    marginTop: hp("1.5%"),
    flex: 1,
    alignItems: "center"
  },
  cartItemLine: {
    borderWidth: 1,
    borderColor: "#e8e8e8",
    width: wp("80%")
  },
  cartImage: {
    width: wp('20%'),
    height: wp('20%'),
    borderRadius: wp("2%"),
    backgroundColor: "#f4f4f4",
  },
  cardImageBox: {
    padding: wp("2%"),
    backgroundColor: "#fff",
    marginRight: wp("2.5%"),
    borderRadius: wp("2%"),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  productDetailsContainer: {
    flex: 1,
    paddingVertical: hp("1%"),
  },
  cartName: {
    justifyContent: "space-between",
    fontSize: wp("3.5%"),
    fontWeight: "600",
    color: "#333",
    flex: 1,
    marginRight: wp("3%"),
  },
  productDesc: {

    fontSize: wp("3.5%"),
    color: '#666',
    
  },
  priceText: {
    fontSize: wp("4%"),
    fontWeight: 'bold',
    color: '#2A3B8F',
  
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    columnGap: wp("5%"),
    marginTop: hp("0.5%"),
  },
  quantityInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: wp("2%"),
    paddingVertical: hp("0.5%"),
    paddingHorizontal: wp("2%"),
    fontSize: wp("4%"),
    fontWeight: '500',
    color: '#333',
    minWidth: wp("12%"),
    textAlign: 'center',
  },
  deleteBtn: {
    padding: wp("1%"),
    backgroundColor: "#fee0e3",
    borderRadius: 50
  },
  checkoutBtnUltraWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: hp("2%"),
    paddingHorizontal: wp("4%"),
    paddingTop: hp("1%"),
    paddingBottom: hp("1%"),
    zIndex: 10,
  },
  checkoutBtnUltra: {
    backgroundColor: "#283593",
    paddingVertical: hp("2%"),
    borderRadius: wp("3%"),
    alignItems: "center",
  },
  checkoutText: {
    color: "#fff",
    fontSize: wp("4.2%"),
    fontWeight: "bold",
  },
  locationContainer: {
    position: 'relative',
    zIndex: 1,
  },
  locationDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: wp("2%"),
    marginTop: hp("0.5%"),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 2,
  },
  locationItem: {
    padding: wp("4%"),
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  locationText: {
    fontSize: wp("4%"),
    color: '#333',
  },
  emptyCartContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: hp("5%"),
    paddingHorizontal: wp("4%"),
  },
  emptyCartCard: {
    backgroundColor: "#fff",
    borderRadius: wp("5%"),
    paddingVertical: hp("5%"),
    paddingHorizontal: wp("5%"),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
  },
  emptyCartImage: {
    width: wp("70%"),
    height: hp("25%"),
    resizeMode: "contain",
    marginBottom: hp("2%"),
  },
  emptyCartTitle: {
    fontSize: wp("5%"),
    fontWeight: "bold",
    color: "#333",
    marginBottom: hp("1%"),
  },
  emptyCartSubtitle: {
    fontSize: wp("4%"),
    color: "#666",
    textAlign: "center",
    marginBottom: hp("3%"),
    paddingHorizontal: wp("5%"),
  },
  exploreButton: {
    backgroundColor: "#283593",
    paddingVertical: hp("1.5%"),
    borderRadius: wp("3%"),
    paddingHorizontal: wp("20%"),
    width: "100%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  exploreButtonText: {
    color: "#fff",
    fontSize: wp("4.2%"),
    fontWeight: "bold",
    textAlign: "center",
    width: "100%",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "white",
    borderRadius: wp("5%"),
    width: wp("85%"),
    paddingTop: hp("6%"),
    paddingBottom: hp("3%"),
    paddingHorizontal: wp("5%"),
    alignItems: "center",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    overflow: 'visible',
  },
  modalDip: {
    position: 'absolute',
    top: -wp("12%"),
    left: wp("25%"),
    right: wp("50%"),
    width: wp("34%"),
    height: wp("34%"),
    borderRadius: wp("20%"),
    backgroundColor: "white",
  },
  trashIconContainer: {
    position: "absolute",
    top: -wp("10%"),
    width: wp("16%"),
    height: wp("16%"),
    borderRadius: wp("8%"),
    backgroundColor: "#FFEBEE",
    borderWidth: 2,
    borderColor: "#EF4444",
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
  },
  modalTitle: {
    fontSize: wp("4.5%"),
    fontWeight: "600",
    textAlign: "center",
    marginBottom: hp("3%"),
    color: "#333",
  },
  modalErrorText: {
    color: "red",
    textAlign: "center",
    marginBottom: hp("1.5%"),
    fontSize: wp("3.8%"),
  },
  modalButtons: {
    width: "100%",
    marginTop: hp("2%"),
  },
  cancelBtn: {
    backgroundColor: "#EF4444",
    paddingVertical: hp("1.8%"),
    borderRadius: wp("2.5%"),
    alignItems: "center",
    marginBottom: hp("1.2%"),
  },
  cancelText: {
    color: "white",
    fontWeight: "600",
    fontSize: wp("4%"),
  },
  confirmBtn: {
    backgroundColor: "#E5E7EB",
    paddingVertical: hp("1.8%"),
    borderRadius: wp("2.5%"),
    alignItems: "center",
  },
  confirmBtnDisabled: {
    backgroundColor: "#FCA5A5",
  },
  confirmText: {
    color: "#374151",
    fontWeight: "600",
    fontSize: wp("4%"),
  },
});




